CREATE TABLE mahasiswa (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    nim VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE dosen (
    id SERIAL PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    nid VARCHAR(20) UNIQUE NOT NULL
);